# Generated by Django 5.2.6 on 2025-09-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("especialization", models.CharField(max_length=50)),
                ("hire_date", models.DateTimeField(auto_now_add=True)),
                ("fired_date", models.DateTimeField(null=True)),
            ],
        ),
    ]
