# Generated by Django 5.2.6 on 2025-11-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medics",
            fields=[
                (
                    "crm",
                    models.CharField(
                        default="0000",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="-", max_length=100)),
                ("especialization", models.CharField(default="-", max_length=100)),
                ("hire_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Aguardando")),
            ],
        ),
    ]
