# Generated by Django 5.2.6 on 2025-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medics",
            name="especialization",
        ),
        migrations.AddField(
            model_name="medics",
            name="spec",
            field=models.CharField(default="Não informado", max_length=100),
        ),
        migrations.AlterField(
            model_name="medics",
            name="crm",
            field=models.CharField(
                default="0000000000",
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="medics",
            name="hire_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="medics",
            name="status",
            field=models.CharField(
                choices=[
                    ("ocupado", "Ocupado"),
                    ("disponivel", "Disponivel"),
                    ("indisponivel", "Indisponivel"),
                    ("aguardando", "Aguardando"),
                ],
                default="aguardando",
                max_length=20,
            ),
        ),
    ]
