# Generated by Django 5.2.6 on 2025-10-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medics", "0001_initial"),
        ("patients", "0002_alter_patients_cpf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medics",
            old_name="fired_date",
            new_name="status",
        ),
        migrations.AddField(
            model_name="medics",
            name="exams",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patients",
            ),
        ),
    ]
