# Generated by Django 5.2.6 on 2025-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medics", "0002_rename_fired_date_medics_status_medics_exams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medics",
            name="id",
        ),
        migrations.AddField(
            model_name="medics",
            name="crm",
            field=models.CharField(
                default="-",
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
