# Generated by Django 5.2.6 on 2025-10-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medics", "0003_remove_medics_id_medics_crm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medics",
            name="crm",
            field=models.CharField(
                default="0000",
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
