# Generated by Django 5.2.6 on 2025-11-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medics", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("ultrassonografia", "Ultrassonografia"),
                            ("ressonância magnética", "Ressonancia magnética"),
                            ("radiografia", "Radiografia"),
                            ("hemograma", "exame de sangue"),
                            ("glicemia em jejum", "Glicemia em jejum"),
                        ],
                        max_length=100,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("scheduled_exam", models.DateTimeField()),
                (
                    "exam_status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("pendente", "Pendente"),
                            ("concluido", "Concluido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="Pendente",
                        max_length=50,
                    ),
                ),
                ("exam_value", models.FloatField(default=0.0)),
                (
                    "pay_status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em andamento"),
                            ("pago", "Pago"),
                        ],
                        default="Pendente",
                        max_length=50,
                    ),
                ),
                (
                    "medic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="medics.medics",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="patients.patients",
                    ),
                ),
            ],
        ),
    ]
