# Generated by Django 5.2.6 on 2025-09-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tittle", models.CharField(max_length=100)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("scheduled_exam", models.DateTimeField()),
                ("realized_exam", models.DateTimeField(null=True)),
            ],
        ),
    ]
