# Generated by Django 5.2.6 on 2025-10-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        ("patients", "0002_alter_patients_cpf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exams",
            old_name="tittle",
            new_name="exam_type",
        ),
        migrations.RemoveField(
            model_name="exams",
            name="realized_exam",
        ),
        migrations.AddField(
            model_name="exams",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="patients.patients",
            ),
        ),
        migrations.AddField(
            model_name="exams",
            name="status",
            field=models.CharField(default="Agendado", null=True),
        ),
    ]
