# Generated by Django 5.2.6 on 2025-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exams",
            name="exam_status",
            field=models.CharField(
                choices=[
                    ("agendado", "Agendado"),
                    ("pendente", "Pendente"),
                    ("concluido", "Concluido"),
                    ("cancelado", "Cancelado"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exams",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("ultrassom", "Ultrassonografia"),
                    ("ressonancia_magnetica", "Ressonância magnética"),
                    ("radiografia", "Radiografia"),
                    ("hemograma", "Exame de sangue"),
                    ("glicemia_jejum", "Glicemia em jejum"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="exams",
            name="pay_status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_andamento", "Em andamento"),
                    ("pago", "Pago"),
                ],
                default="pendente",
                max_length=50,
            ),
        ),
    ]
