# Generated by Django 5.2.6 on 2025-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_rename_tittle_exams_exam_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exams",
            name="exam_value",
            field=models.FloatField(default=0.0),
        ),
    ]
