# Generated by Django 5.2.6 on 2025-11-30 15:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_exams_exam_status_alter_exams_exam_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exams",
            name="exam_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
