# Generated by Django 5.2.6 on 2025-11-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "cpf",
                    models.CharField(
                        max_length=11, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.SmallIntegerField()),
                ("addres", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
    ]
