# Generated by Django 5.2.6 on 2025-09-26 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid CPF",
                                message="CPF deve conter 11 dígitos numéricos",
                                regex="^\\d{11}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.SmallIntegerField()),
                ("addres", models.CharField(max_length=100)),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
