# Generated by Django 5.2.6 on 2025-10-02 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="cpf",
            field=models.CharField(
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid CPF",
                        message="CPF deve conter 11 dígitos numéricos",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="CPF",
            ),
        ),
    ]
