# Generated by Django 5.2.6 on 2025-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patients_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="cpf",
            field=models.CharField(
                max_length=11, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="phone",
            field=models.CharField(),
        ),
    ]
